### PR TITLE
Add 32-bit installers

### PR DESCRIPTION
**Pull request by CIO61**

### CODE REVIEW

**Comment by Krarilotus** [comment]
Is there a way to detect if the users windows is 32 or 64 bit?

**Comment by CIO61** [comment]
there should be, but this PR does not take that into account, it just makes giving support to 32-bit users easier(by telling them to manually install using the other .bat)

**Comment by CIO61** [comment]
it seems there is, so we may update this to actually determine and choose the exe to mod the game accordingly: https://stackoverflow.com/questions/601089/detect-whether-current-windows-version-is-32-bit-or-64-bit#1833044
```@echo off
if defined ProgramFiles(x86) (
    @echo yes
    @echo Some 64-bit work
) else (
    @echo no
    @echo Some 32-bit work
)```

**Comment by CIO61** [comment]
will-re open a PR with the functionality

**Pull request closed without merging**
